# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "julia"
    directories:
      - "/"
      - "/docs"
      - "/test"
    schedule:
      interval: "weekly"

